name: contentful_flutter
description: The Contentful Flutter SDK is a Dart package that allows you to access the Contentful Content Delivery API from your Flutter app.

# Add the changes in CHANGELOG.md when the version changes
version: 0.0.13
repository: https://github.com/hackberrybay/contentful_flutter
homepage: https://hackberry.se

environment:
  sdk: ">=3.3.0 <4.0.0"

dependency_overrides: 
  collection: ^1.19.1

dependencies:
  flutter:
    sdk: flutter
  # ... Code generation ...
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  # ... Network ...
  http: ^1.6.0
  retry: ^3.1.2
  fpdart: ^1.2.0 # Functional programming to use the Either<> type
  collection: ^1.19.1
  logger: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0
  # ... Code generation ...
  freezed: ^3.2.5
  json_serializable: ^6.9.0
  build_runner: ^2.13.0
  # ... Linting ...
  lints: ^6.1.0

topics:
  - contentful
  - platform
  - cms
  - article
  - blog

screenshots:
  - description: The contentful_flutter demo
    path: screenshots/example_app.png